version: "3"

services:
  # Puppet - Main Server
  puppet:
    image: puppet/puppetserver:${PUPPET_SERVER_TAG:-latest}
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      # The mounted onto path '/conjur' is a proxy location that allows us to decide, at
      # runtime, between installing the packaged module or using the module source.
      - ../../.:/conjur
    # In some environments puppetdb host gets cert for puppetdb.local.
    # Make sure the connection works either way.
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb-main:8081
    depends_on:
      - puppetdb-main

  postgres-main:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb-main
      - POSTGRES_USER=puppetdb-main
      - POSTGRES_DB=puppetdb-main
    expose:
      - 5432

  puppetdb-main:
    image: puppet/puppetdb
    environment:
      - CERTNAME=puppetdb-main
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETDB_POSTGRES_DATABASE=puppetdb-main
      - PUPPETDB_POSTGRES_HOSTNAME=postgres-main
      - PUPPETDB_PASSWORD=puppetdb-main
      - PUPPETDB_USER=puppetdb-main
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres-main

  # Puppet tools
  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8081:8000

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 8080:80
    read_only: true

  # Conjur OSS
  conjur:
    image: cyberark/conjur
    ports:
      - 80
    environment:
      CONJUR_ADMIN_PASSWORD: ADmin123!!!!
      DATABASE_URL: postgres://postgres@conjur-db
      CONJUR_DATA_KEY: testing//testing//testing//testing//testing=
    volumes:
      - .:/src:ro
    working_dir: /src
    command: server
    depends_on:
      - conjur-db

  conjur-db:
    image: postgres:9.3

  conjur-https:
    image: nginx:alpine
    ports:
      - 8443
    volumes:
      - ./https_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./https_config/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./https_config/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./https_config/conjur.crt:/cert/tls.crt:ro
      - ./https_config/conjur.key:/cert/tls.key:ro
      - ./https_config/ca.crt:/ca/tls.crt:ro
    depends_on:
      - conjur

  cli:
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_APPLIANCE_URL: http://conjur
    image: cyberark/conjur-cli:5
    entrypoint: sleep
    command: infinity
    volumes:
      - .:/src:ro
