version: "3"

services:
  puppet:
    image: puppet/puppetserver:${PUPPET_SERVER_TAG:-latest}
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ../../.:/etc/puppetlabs/code/environments/production/modules/conjur
    # In some environments puppetdb host gets cert for puppetdb.local.
    # Make sure the connection works either way.
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb.local:8081,https://puppetdb:8081
    links:
      - puppetdb:puppetdb.local
    depends_on:
      - puppetdb

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432

  puppetdb:
    image: puppet/puppetdb
    environment:
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETDB_POSTGRES_HOSTNAME=postgres
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8081:8000

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 8080:80
    read_only: true

  conjur:
    image: cyberark/conjur
    environment:
      CONJUR_ADMIN_PASSWORD: ADmin123!!!!
      DATABASE_URL: postgres://postgres@db
      CONJUR_DATA_KEY: testing//testing//testing//testing//testing=
    volumes:
      - .:/src:ro
    working_dir: /src
    command: server
    depends_on:
      - db

  db:
    image: postgres:9.3

  cli:
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_APPLIANCE_URL: http://conjur
    image: cyberark/conjur-cli:5
    entrypoint: sleep
    command: infinity
    volumes:
      - .:/src:ro
